#!/bin/sh
# vim:ts=2:sw=2:et

set -e

dpkg-maintscript-helper rm_conffile /etc/kernel/postinst.d/linux-firmware-raspi3 1.20161123-2 -- "$@"

true "INFO: debhelper beginning here."

#DEBHELPER#

true "INFO: Done with debhelper."

exit 0
